name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: shenron
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyscaffold
          pip install tox

      - name: Run tests and build docs
        run: |
          tox
          tox -e docs

  version_bump:
    runs-on: shenron
    needs: build
    if: |
      contains(github.event.head_commit.message, '#minor') ||
      contains(github.event.head_commit.message, '#patch') ||
      contains(github.event.head_commit.message, '#major')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release_branches: main
          DEFAULT_BUMP: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish:
    runs-on: shenron
    needs: [build, version_bump]
    if: |
      contains(github.event.head_commit.message, '#patch') || 
      contains(github.event.head_commit.message, '#minor') ||
      contains(github.event.head_commit.message, '#major')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*

  deploy_docs:
    runs-on: shenron
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/_build/html
